### ISSUE TITLE
Using the simple "test" blocks result display

### ISSUE THREAD

**Issue by cgravill** [adamchester/expecto-adapter#31] opened 2017-11-08 16:59 UTC
I'm trying to use the test adaptor as it'd be great to use Expecto more. I don't seem to be able to use the `test` to create simple cases.

```fsharp
open Expecto

[<Tests>]
let tests =
    testList "samples" [

        testCase "universe exists" <| fun _ ->
            let subject = true
            Expect.isTrue subject "I compute, therefore I am."

        test "A simple test" {
            let subject = "Hello World"
            Expect.equal subject "Hello World" "The strings should equal"
        }

        testCase "After a simple test" <| fun _ ->
            let subject = true
            Expect.isTrue subject "Not seen."
    ]

[<EntryPoint>]
let main args =
  runTestsWithArgs defaultConfig args tests
```

Leads to the the simple `test` and subsequent `testCase` not being displayed.

The tests are being run from the log though:

```
[2017-11-08 16:56:11 Informational] ------ Run test started ------
[2017-11-08 16:56:12 Informational] Running all tests (9999.0.0.0)
[2017-11-08 16:56:12 Informational] Creating test host for #####\Testy\Testy\bin\Debug\Testy.exe
[2017-11-08 16:56:12 Informational] Executing tests in assembly #####\Testy\Testy\bin\Debug\Testy.exe
[2017-11-08 16:56:12 Informational] Executing all tests in #####\Testy\Testy\bin\Debug\Testy.exe
[2017-11-08 16:56:12 Informational] All tests: 3
[2017-11-08 16:56:12 Informational] Number of tests included: 3
[2017-11-08 16:56:12 Informational] starting 'samples/universe exists'
[2017-11-08 16:56:12 Informational] starting 'samples/After a simple test'
[2017-11-08 16:56:12 Informational] starting 'samples/A simple test'
[2017-11-08 16:56:12 Informational] summary {results =
  [({name = "samples/universe exists";
     test = Sync <fun:tests@7>;
     state = Normal;
     focusOn = false;
     sequenced = InParallel;}, {result = Passed;
                                count = 1;
                                meanDuration = 3.0;
                                maxDuration = 3.0;
                                totalVariance = 0.0;});
   ({name = "samples/A simple test";
     test = Sync <fun:tests@12-1>;
     state = Normal;
     focusOn = false;
     sequenced = InParallel;}, {result = Passed;
                                count = 1;
                                meanDuration = 5.0;
                                maxDuration = 5.0;
                                totalVariance = 0.0;});
   ({name = "samples/After a simple test";
     test = Sync <fun:tests@16-34>;
     state = Normal;
     focusOn = false;
     sequenced = InParallel;}, {result = Passed;
                                count = 1;
                                meanDuration = 3.0;
                                maxDuration = 3.0;
                                totalVariance = 0.0;})];
 duration = 00:00:00.1374515;
 maxMemory = 0L;
 memoryLimit = 0L;
 timedOut = [];}
[2017-11-08 16:56:12 Error] Test adapter sent back a result for an unknown test case. Ignoring result for 'samples/After a simple test'.
[2017-11-08 16:56:12 Error] Test adapter sent back a result for an unknown test case. Ignoring result for 'samples/A simple test'.
[2017-11-08 16:56:12 Informational] ========== Run test finished: 1 run (0:00:01.021702) ==========
```

I tried building from master but had the same missing tests:

![image](https://user-images.githubusercontent.com/1099725/32562270-1bf7caf0-c4a6-11e7-91e4-470d4db0cf84.png)

**Comment by MNie** [comment] 2017-11-21 21:28
@cgravill 
I trying to reproduce your problem and I have the same issue
![image](https://user-images.githubusercontent.com/7689103/33097405-641b633c-cf0a-11e7-8cc4-9d601d8a243a.png)
But when assertion in single test is different than `Expect.equal` for example `Expect.isTrue`/`Expect.isEmpty` then everything works fine:
![image](https://user-images.githubusercontent.com/7689103/33097464-91676ba6-cf0a-11e7-8498-708dfe760617.png)
![image](https://user-images.githubusercontent.com/7689103/33097548-ddd41b24-cf0a-11e7-8daf-6d6db2d0c9f7.png)
So it looks like there is a problem with simple test where assertion is `Expecto.equal` I will check in a free time if it's a problem with adapter or expecto itself.

**Comment by cgravill** [comment] 2017-11-22 16:57
Thanks for confirming. It'd be great to run tests with Visual Studio as well as it's easier to select a given test that way than via the command-line.

**Comment by MNie** [comment] 2017-12-18 20:58
@cgravill sorry for a late response. I try to discover from where this bug comes from, but when I run those tests one more time, everything works fine..
![image](https://user-images.githubusercontent.com/7689103/34127582-f872500c-e43d-11e7-8c64-bc4e5347d1ab.png)
The same with runTestsWithArgs:
![image](https://user-images.githubusercontent.com/7689103/34127610-10ef0666-e43e-11e7-96fe-3287d4a6600f.png)
The only thing which I did, since the last attempt was an update of Mono.Cecil library from: [0.10.0-beta5](https://www.nuget.org/packages/Mono.Cecil/0.10.0-beta5) to [0.10.0-beta7](https://www.nuget.org/packages/Mono.Cecil/0.10.0-beta7) could you confirm if it also helps you?

**Comment by MNie** [comment] 2017-12-19 09:32
In fact this issue seems to be a duplicate of #28 . New version of adapter released to nuget, update of mono.cecil should fix'd the issue.

**Closed by MNie** 2017-12-19 09:32 UTC
Labels: bug
